/** Curated IATA airline code -> name lookup, covering common carriers.
 * Unknown codes just fall back to the raw code, so this list doesn't need
 * to be exhaustive. */
export const AIRLINES: Record<string, string> = {
  AA: "American Airlines",
  UA: "United Airlines",
  DL: "Delta Air Lines",
  WN: "Southwest Airlines",
  AS: "Alaska Airlines",
  B6: "JetBlue",
  NK: "Spirit Airlines",
  F9: "Frontier Airlines",
  HA: "Hawaiian Airlines",
  AC: "Air Canada",
  BA: "British Airways",
  VS: "Virgin Atlantic",
  AF: "Air France",
  KL: "KLM",
  LH: "Lufthansa",
  LX: "Swiss International Air Lines",
  OS: "Austrian Airlines",
  SN: "Brussels Airlines",
  IB: "Iberia",
  TP: "TAP Air Portugal",
  AZ: "ITA Airways",
  AY: "Finnair",
  SK: "SAS",
  DY: "Norwegian Air",
  FR: "Ryanair",
  U2: "easyJet",
  W6: "Wizz Air",
  VY: "Vueling",
  EI: "Aer Lingus",
  TK: "Turkish Airlines",
  LO: "LOT Polish Airlines",
  OK: "Czech Airlines",
  A3: "Aegean Airlines",
  EW: "Eurowings",
  QR: "Qatar Airways",
  EK: "Emirates",
  EY: "Etihad Airways",
  SV: "Saudia",
  MS: "EgyptAir",
  ET: "Ethiopian Airlines",
  SA: "South African Airways",
  KQ: "Kenya Airways",
  SQ: "Singapore Airlines",
  CX: "Cathay Pacific",
  JL: "Japan Airlines",
  NH: "All Nippon Airways",
  KE: "Korean Air",
  OZ: "Asiana Airlines",
  CA: "Air China",
  MU: "China Eastern",
  CZ: "China Southern",
  TG: "Thai Airways",
  MH: "Malaysia Airlines",
  GA: "Garuda Indonesia",
  PR: "Philippine Airlines",
  VN: "Vietnam Airlines",
  AI: "Air India",
  QF: "Qantas",
  NZ: "Air New Zealand",
  VA: "Virgin Australia",
  LA: "LATAM Airlines",
  AM: "Aeromexico",
  AV: "Avianca",
  CM: "Copa Airlines",
  G3: "Gol Linhas Aereas",
  AD: "Azul Brazilian Airlines",
  IB2: "Iberia Express",
  WF: "Widerøe",
  AB: "Air Berlin",
  PC: "Pegasus Airlines",
  XQ: "SunExpress",
  BT: "airBaltic",
  FI: "Icelandair",
  UX: "Air Europa",
  TU: "Tunisair",
  RJ: "Royal Jordanian",
  ME: "Middle East Airlines",
  GF: "Gulf Air",
  WY: "Oman Air",
  "9W": "Jet Airways",
  "6E": "IndiGo",
  SG: "SpiceJet",
};

export function lookupAirline(code: string): string {
  return AIRLINES[code.toUpperCase()] ?? code.toUpperCase();
}

export function isKnownAirlineCode(code: string): boolean {
  return code.toUpperCase() in AIRLINES;
}
